# Generated by Django 5.0.2 on 2024-02-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
